"""
webqsp.py – GraphContainer adapter for the WebQSP dataset preprocessed by G-Retriever.

Dataset layout expected at *source* path
(default: dataset/webqsp/ inside the G-Retriever repo):

    nodes/{idx}.csv      – columns: node_id, node_attr
    edges/{idx}.csv      – columns: src, edge_attr, dst
    graphs/{idx}.pt      – torch_geometric Data objects with .x / .edge_attr embeddings
    split/
        train_indices.txt
        val_indices.txt
        test_indices.txt
    questions.csv        – auto-generated by this adapter on first import (if absent)
                           columns: question, image_id, answer, split

Questions and answers are sourced from the HuggingFace dataset
``rmanluo/RoG-webqsp`` (train + validation + test), concatenated in the
same order used by the G-Retriever pre-processing script.

Oracle resolution:
    The g_retriever oracle style is reused.  It maps
    ``norm(question) → image_id (= graph index)`` via ``questions.csv``,
    then loads all ``node_attr`` values from ``nodes/{image_id}.csv`` as
    gold nodes.  Because the per-question subgraph is the gold context in
    WebQSP (the graph IS the oracle), this gives exact gold-node coverage.

Usage:
    python serve.py --format webqsp --source /mnt/disk2/cjhyun/G-Retriever/dataset/webqsp
"""

from __future__ import annotations

import csv
import json

# Increase CSV field size limit for large attributes
csv.field_size_limit(10 * 1024 * 1024)  # 10MB
import os
import sys
import types
from hashlib import md5
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from tqdm import tqdm

from ..core import SearchableGraphContainer, SimpleGraphContainer
from ..types import EdgeRecord, NodeRecord
from ..utils import container_or_new
from .base import GraphAdapter, GraphAdapterError, UnsupportedSourceError
from .g_retriever import (
    _ensure_tg_stubs,
    _flush_upsert,
    _iter_graph_batches,
    _list_graph_ids,
    _load_pt_embeddings,
    _normalize_text,
    _append_unique,
    _torch,
)
from ..indexers import ChromaCollectionIndexer


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _normalize_source(source: Any) -> Path:
    if isinstance(source, (str, Path)):
        return Path(source)
    raise UnsupportedSourceError(f"Unsupported source type: {type(source)}")


def _load_hf_dataset(dataset_name: str = "rmanluo/RoG-webqsp"):
    """Load and concatenate train/validation/test splits from HuggingFace."""
    try:
        from datasets import load_dataset, concatenate_datasets
    except ImportError:
        raise ImportError(
            "The 'datasets' package is required to load WebQSP questions. "
            "Install it with: pip install datasets"
        )
    dataset = load_dataset(dataset_name)
    parts = [dataset[split] for split in ("train", "validation", "test") if split in dataset]
    if not parts:
        raise UnsupportedSourceError(
            f"No expected splits found in '{dataset_name}'. Available: {list(dataset.keys())}"
        )
    return concatenate_datasets(parts) if len(parts) > 1 else parts[0]


def _generate_questions_csv(src_path: Path, dataset_name: str = "rmanluo/RoG-webqsp") -> Path:
    """
    Generate ``questions.csv`` in *src_path* by fetching questions/answers from
    HuggingFace.  Skips generation if the file already exists.

    Returns the path to the generated (or existing) ``questions.csv``.
    """
    questions_csv = src_path / "questions.csv"
    if questions_csv.exists():
        print(f"[WebQSP] questions.csv already exists at {questions_csv}, skipping generation.")
        return questions_csv

    print(f"[WebQSP] Generating questions.csv from HuggingFace '{dataset_name}' ...")

    split_dir = src_path / "split"
    split_indices: Dict[str, set] = {}
    for split_name in ("train", "val", "test"):
        fname = split_dir / f"{split_name}_indices.txt"
        if fname.exists():
            with fname.open("r") as f:
                split_indices[split_name] = {int(l.strip()) for l in f if l.strip()}

    def _get_split(idx: int) -> str:
        for split_name, indices in split_indices.items():
            if idx in indices:
                return split_name
        return "unknown"

    hf_data = _load_hf_dataset(dataset_name)

    with questions_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["question", "image_id", "answer", "split"])
        for idx, row in enumerate(tqdm(hf_data, desc="Writing questions.csv")):
            question = str(row.get("question", "")).strip()
            answers = row.get("answer", [])
            if isinstance(answers, list):
                answer_str = "|".join(str(a).lower() for a in answers)
            else:
                answer_str = str(answers).lower()
            split_name = _get_split(idx)
            writer.writerow([question, str(idx), answer_str, split_name])

    print(f"[WebQSP] Wrote {len(hf_data)} questions to {questions_csv}")
    return questions_csv


# ---------------------------------------------------------------------------
# Adapter
# ---------------------------------------------------------------------------

class WebQSPAdapter(GraphAdapter):
    """
    Adapter for the WebQSP dataset preprocessed by G-Retriever.

    This is a thin wrapper around the GRetriever pipeline that additionally
    generates a ``questions.csv`` file (needed by the g_retriever oracle) the
    first time the dataset is imported.
    """

    def __init__(self):
        super().__init__(name="webqsp", version="0.1.0")

    def can_import(self, source: Any) -> bool:
        try:
            src = _normalize_source(source)
            has_csv_dirs = (src / "nodes").is_dir() and (src / "edges").is_dir()
            if not has_csv_dirs:
                return False
            graphs_dir = src / "graphs"
            if not graphs_dir.is_dir():
                return False
            if not any(graphs_dir.glob("*.pt")):
                return False
            return True
        except Exception:
            return False

    def import_graph(
        self,
        source: Any,
        container: Optional[SimpleGraphContainer] = None,
        *,
        keep_source_reference: bool = False,
        attach_index: Optional[bool] = None,
        hf_dataset_name: str = "rmanluo/RoG-webqsp",
        **kwargs: Any,
    ) -> SearchableGraphContainer:
        """
        Import the WebQSP dataset.

        Args:
            source: Path to the dataset root containing ``nodes/``, ``edges/``,
                ``graphs/`` directories.
            container: Optional pre-existing container to populate.
            keep_source_reference: Store ``_source_path`` / ``_source_style``
                metadata on every node/edge.
            attach_index: Whether to upsert ``.pt`` embeddings into ChromaDB.
                Defaults to ``GRETRIEVER_ATTACH_INDEX`` env-var (True when unset).
            hf_dataset_name: HuggingFace dataset name used to fetch questions.
                Defaults to ``"rmanluo/RoG-webqsp"``.
        """
        def _env_bool(name: str, default: bool) -> bool:
            raw = os.getenv(name)
            if raw is None:
                return default
            return raw.strip().lower() in {"1", "true", "yes", "y", "on"}

        if attach_index is None:
            attach_index = _env_bool("GRETRIEVER_ATTACH_INDEX", True)
        batch_size = int(os.getenv("GRETRIEVER_BATCH_SIZE", "100"))
        db_path = os.getenv("VECTOR_STORE_PATH", "./data/database/chroma_db")
        distance_metric = os.getenv("VECTOR_DISTANCE_METRIC", "cosine")

        src_path = _normalize_source(source)
        graph = container_or_new(container)

        # ------------------------------------------------------------------ #
        # 0. Generate questions.csv (needed by the oracle)                    #
        # ------------------------------------------------------------------ #
        try:
            _generate_questions_csv(src_path, hf_dataset_name)
        except Exception as exc:
            print(f"[WebQSP] WARNING: Could not generate questions.csv: {exc}")
            print("[WebQSP] Oracle node highlighting will not be available.")

        # ------------------------------------------------------------------ #
        # 1. Set up ChromaDB collections                                       #
        # ------------------------------------------------------------------ #
        node_col = None
        edge_col = None
        if attach_index:
            try:
                import chromadb
                base_name = src_path.resolve().name
                db_dir = Path(db_path).resolve()
                db_dir.mkdir(parents=True, exist_ok=True)
                try:
                    _chroma_client = chromadb.PersistentClient(path=str(db_dir))
                except Exception:
                    _chroma_client = chromadb.EphemeralClient()
                    db_path = None
                node_col = _chroma_client.get_or_create_collection(
                    name=f"{base_name}_nodes"
                )
                edge_col = _chroma_client.get_or_create_collection(
                    name=f"{base_name}_edges"
                )
            except ImportError:
                node_col = None
                edge_col = None

        # Upsert accumulation buffers
        node_ids: List[str] = []
        node_embs: List[List[float]] = []
        node_docs: List[str] = []
        node_metas: List[Dict[str, Any]] = []
        node_ids_seen: set = set()

        edge_ids_buf: List[str] = []
        edge_embs_buf: List[List[float]] = []
        edge_docs_buf: List[str] = []
        edge_metas_buf: List[Dict[str, Any]] = []

        # ------------------------------------------------------------------ #
        # 2. Load all graph IDs and iterate                                    #
        # ------------------------------------------------------------------ #
        graph_ids = _list_graph_ids(src_path)
        print(f"[DEBUG] WebQSP src_path: {src_path}")
        print(f"[DEBUG] Found {len(graph_ids)} graph IDs")
        
        node_key_to_global: Dict[Tuple[str, str], str] = {}
        edge_key_to_idx: Dict[Tuple[str, str, str], int] = {}
        graphs_dir = src_path / "graphs"

        # Use graph-level tqdm for better feedback
        pbar = tqdm(total=len(graph_ids), desc="Loading WebQSP graphs", unit="graph")
        
        for gid_batch, node_rows_batch, edge_rows_batch, x_batch, ea_batch in _iter_graph_batches(
            graph_ids, src_path, graphs_dir, batch_size, skip_embeddings=(not attach_index)
        ):
            for gid, node_rows, edge_rows, x_tensor, edge_attr_tensor in zip(
                gid_batch, node_rows_batch, edge_rows_batch, x_batch, ea_batch
            ):
                pbar.update(1)

                local_to_global: Dict[str, str] = {}

                # ── Nodes ─────────────────────────────────────────────────
                for row_idx, raw in enumerate(node_rows):
                    node_id = raw.get("node_id") or raw.get("id")
                    if node_id is None or str(node_id).strip() == "":
                        continue

                    node_text = raw.get("node_attr", raw.get("text"))
                    node_type = str(raw.get("type", "Entity"))
                    local_id = str(node_id)
                    node_key_text = _normalize_text(node_text)

                    if node_key_text:
                        node_key = (node_type.lower(), node_key_text)
                        default_global_id = f"node-{md5(f'{node_key[0]}|{node_key[1]}'.encode()).hexdigest()}"
                    else:
                        node_key = ("__fallback__", f"{gid}:{local_id}")
                        default_global_id = f"{gid}:{local_id}"

                    global_id = node_key_to_global.get(node_key, default_global_id)
                    local_to_global[local_id] = global_id

                    node_emb: Optional[List[float]] = None
                    if x_tensor is not None and row_idx < x_tensor.shape[0]:
                        try:
                            node_emb = x_tensor[row_idx].tolist()
                        except Exception:
                            node_emb = None

                    if global_id in graph.nodes:
                        existing_meta = graph.nodes[global_id].metadata
                        _append_unique(existing_meta, "graph_ids", str(gid))
                        _append_unique(existing_meta, "original_node_ids", f"{gid}:{local_id}")
                        if node_emb is not None and graph.nodes[global_id].embedding is None:
                            graph.nodes[global_id].embedding = node_emb
                    else:
                        metadata: Dict[str, Any] = {
                            k: v
                            for k, v in raw.items()
                            if k not in {"node_id", "id", "node_attr", "text", "type"}
                        }
                        metadata["graph_ids"] = [str(gid)]
                        metadata["original_node_ids"] = [f"{gid}:{local_id}"]
                        if keep_source_reference:
                            metadata.setdefault("_source_path", str(src_path))
                            metadata.setdefault("_source_style", "webqsp")

                        graph.add_node(
                            NodeRecord(
                                id=global_id,
                                type=node_type,
                                text=node_text,
                                embedding=node_emb,
                                metadata=metadata,
                            )
                        )
                        node_key_to_global[node_key] = global_id

                    if node_col is not None and node_emb is not None and global_id not in node_ids_seen:
                        node_ids_seen.add(global_id)
                        node_ids.append(global_id)
                        node_embs.append(node_emb)
                        node_docs.append(str(node_text or ""))
                        node_metas.append({"graph_id": str(gid), "local_id": local_id})
                        if len(node_ids) >= batch_size:
                            _flush_upsert(node_col, node_ids, node_embs, node_docs, node_metas)
                            node_ids_seen.clear()

                # ── Edges ─────────────────────────────────────────────────
                for row_idx, raw in enumerate(edge_rows):
                    source_id = raw.get("src", raw.get("source"))
                    target_id = raw.get("dst", raw.get("target"))
                    if source_id is None or target_id is None:
                        continue

                    src_local = str(source_id)
                    tgt_local = str(target_id)
                    source_global = local_to_global.get(src_local, f"{gid}:{src_local}")
                    target_global = local_to_global.get(tgt_local, f"{gid}:{tgt_local}")
                    relation = str(raw.get("edge_attr", raw.get("relation", "related")))
                    try:
                        weight = float(raw.get("weight", 1.0))
                    except (TypeError, ValueError):
                        weight = 1.0

                    edge_emb: Optional[List[float]] = None
                    if edge_attr_tensor is not None and row_idx < edge_attr_tensor.shape[0]:
                        try:
                            edge_emb = edge_attr_tensor[row_idx].tolist()
                        except Exception:
                            edge_emb = None

                    edge_key = (source_global, relation, target_global)
                    if edge_key in edge_key_to_idx:
                        edge_idx = edge_key_to_idx[edge_key]
                        existing_edge = graph.edges[edge_idx]
                        if existing_edge.weight < weight:
                            existing_edge.weight = weight
                        _append_unique(existing_edge.metadata, "graph_ids", str(gid))
                        _append_unique(
                            existing_edge.metadata,
                            "original_edge_ids",
                            f"{gid}:{src_local}->{tgt_local}",
                        )
                        continue

                    edge_metadata: Dict[str, Any] = {
                        k: v
                        for k, v in raw.items()
                        if k not in {"src", "source", "dst", "target", "edge_attr", "relation", "weight"}
                    }
                    edge_metadata["graph_ids"] = [str(gid)]
                    edge_metadata["original_edge_ids"] = [f"{gid}:{src_local}->{tgt_local}"]
                    if keep_source_reference:
                        edge_metadata.setdefault("_source_path", str(src_path))
                        edge_metadata.setdefault("_source_style", "webqsp")

                    graph.add_edge(
                        EdgeRecord(
                            source=source_global,
                            target=target_global,
                            relation=relation,
                            weight=weight,
                            metadata=edge_metadata,
                        )
                    )
                    edge_key_to_idx[edge_key] = len(graph.edges) - 1

                    if edge_col is not None and edge_emb is not None:
                        edge_id = f"{gid}:{row_idx}:{src_local}->{tgt_local}"
                        edge_ids_buf.append(edge_id)
                        edge_embs_buf.append(edge_emb)
                        edge_docs_buf.append(f"{source_global} {relation} {target_global}")
                        edge_metas_buf.append({
                            "graph_id": str(gid),
                            "source": source_global,
                            "target": target_global,
                            "relation": relation,
                        })
                        if len(edge_ids_buf) >= batch_size:
                            _flush_upsert(edge_col, edge_ids_buf, edge_embs_buf, edge_docs_buf, edge_metas_buf)

            # Flush at end of each tqdm batch
            if node_col is not None and node_ids:
                _flush_upsert(node_col, node_ids, node_embs, node_docs, node_metas)
                node_ids_seen.clear()
            if edge_col is not None and edge_ids_buf:
                _flush_upsert(edge_col, edge_ids_buf, edge_embs_buf, edge_docs_buf, edge_metas_buf)

        # ------------------------------------------------------------------ #
        # 3. Final flush + attach indices                                       #
        # ------------------------------------------------------------------ #
        if node_col is not None:
            _flush_upsert(node_col, node_ids, node_embs, node_docs, node_metas)
            node_ids_seen.clear()
            graph.attach_index(
                "node_vector",
                ChromaCollectionIndexer(
                    node_col,
                    persist_path=db_path,
                    distance_metric=str(distance_metric),
                ),
            )
        if edge_col is not None:
            _flush_upsert(edge_col, edge_ids_buf, edge_embs_buf, edge_docs_buf, edge_metas_buf)
            graph.attach_index(
                "edge_vector",
                ChromaCollectionIndexer(
                    edge_col,
                    persist_path=db_path,
                    distance_metric=str(distance_metric),
                ),
            )

        return graph

    def export_graph(
        self,
        container: SimpleGraphContainer,
        destination: Any,
        *,
        overwrite: bool = False,
        **kwargs: Any,
    ) -> Dict[str, Any]:
        dest = Path(destination)
        if dest.exists() and not overwrite and any(dest.iterdir()):
            raise GraphAdapterError(f"Destination is not empty: {dest}")
        dest.mkdir(parents=True, exist_ok=True)

        node_path = dest / "nodes.jsonl"
        edge_path = dest / "edges.jsonl"

        with node_path.open("w", encoding="utf-8") as f:
            for node in container.nodes.values():
                payload = {
                    "id": node.id,
                    "text": node.text,
                    "type": node.type,
                    **node.metadata,
                }
                if node.embedding is not None:
                    payload["embedding"] = (
                        node.embedding.tolist()
                        if hasattr(node.embedding, "tolist")
                        else list(node.embedding)
                    )
                f.write(json.dumps(payload, ensure_ascii=False) + "\n")

        with edge_path.open("w", encoding="utf-8") as f:
            for edge in container.edges:
                payload = {
                    "source": edge.source,
                    "target": edge.target,
                    "relation": edge.relation,
                    "weight": edge.weight,
                    **edge.metadata,
                }
                f.write(json.dumps(payload, ensure_ascii=False) + "\n")

        return {
            "destination": str(dest),
            "node_file": str(node_path),
            "edge_file": str(edge_path),
            "nodes": len(container.nodes),
            "edges": len(container.edges),
        }


# ---------------------------------------------------------------------------
# Convenience wrapper
# ---------------------------------------------------------------------------

def import_graph_from_webqsp(
    source: Any,
    *,
    container: Optional[SimpleGraphContainer] = None,
    keep_source_reference: bool = False,
    attach_index: Optional[bool] = None,
    hf_dataset_name: str = "rmanluo/RoG-webqsp",
    **kwargs: Any,
) -> SearchableGraphContainer:
    """
    Convenience wrapper around :class:`WebQSPAdapter`.

    Args:
        source: Path to the preprocessed WebQSP dataset directory
            (containing ``nodes/``, ``edges/``, ``graphs/`` subdirectories).
        container: Optional existing container to populate.
        keep_source_reference: Store ``_source_path`` / ``_source_style`` on
            every node and edge.
        attach_index: Upsert ``.pt`` embeddings into ChromaDB.  Defaults to
            the ``GRETRIEVER_ATTACH_INDEX`` env-var (True when unset).
        hf_dataset_name: HuggingFace dataset identifier used to fetch
            questions/answers.  Defaults to ``"rmanluo/RoG-webqsp"``.
    """
    return WebQSPAdapter().import_graph(
        source=source,
        container=container,
        keep_source_reference=keep_source_reference,
        attach_index=attach_index,
        hf_dataset_name=hf_dataset_name,
        **kwargs,
    )
